name: Deploy to EC2 and Push to ECR

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  ECR_REGISTRY: ${{secrets.ECR_REGISTRY}}
  ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
  IMAGE_TAG: latest
  EC2_HOST: ${{secrets.EC2_HOST}}
  EC2_USER: ${{secrets.EC2_USER}}
  AWS_ID: ${{secrets.AWS_ID}}
  CONTAINER_NAME: ${{secrets.CONTAINER_NAME}}
  ECR_REPO_URI: ${{secrets.ECR_REPO_URI}}
  PORT: 8080

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: build the app
        run: mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{secrets.AWS_KEY_ID}}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws configure set region ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build Multi-Platform Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push .

      - name: Deploy on EC2
        run: |
          echo "${{secrets.EC2_KEY_PAIR}}" > my-key
          chmod 600 my-key
          ssh -i my-key -o StrictHostKeyChecking=no ${{secrets.AWS_USERNAME_AND_IP_ADDRESS}} << EOF
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
          
          if [ "${{ github.ref_name }}" = "dev" ]; then
            PROFILE=dev
            PORT=8085
          else
            echo "Invalid branch name. Exiting..."
            exit 1
          fi
            docker stop ${{env.CONTAINER_NAME}} || true
            docker rm ${{env.CONTAINER_NAME}} || true
            docker pull ${{env.ECR_REPO_URI}}:${{ env.IMAGE_TAG }}
            docker run --name ${{env.CONTAINER_NAME}} -d -p ${{env.PORT}}:${{env.PORT}} \
            -e SPRING_PROFILES_ACTIVE=\$PROFILE \
            ${{env.ECR_REPO_URI}}:${{ env.IMAGE_TAG }}
          EOF